### ISSUE TITLE
help!!! your plugin crashes an entire WP site

### ISSUE THREAD

**Issue by PieterCooreman** [itthinx/groups#130]
and disabling it exposes very sensitve data to the public and search engines...

this is a disaster. please help. let me know what I can do to help you to help me.

Groups version: 2.16.1 
WordPress 5.9

**Comment by itthinx** [comment]
Please make sure that you have debugging enabled and provide details from your site's debug.log so we can see what exact issue you have on your site.

**Comment by PieterCooreman** [comment]
Een fout van het type E_PARSE werd veroorzaakt op regelnummer 243 van het bestand /home/XXXX/domains/XXXXX/public_html/XXX/wp-content/plugins/groups/lib/admin/groups-admin-options.php. Foutmelding: syntax error, unexpected ''

**Comment by itthinx** [comment]
This points to https://github.com/itthinx/groups/blob/master/lib/admin/groups-admin-options.php#L243 which makes no sense unless your files have been corrupted.

If that is the case, you might want to replace your copy of the plugin with the untouched latest release. You can do that by deleting the folder wp-content/plugins/groups and installing Groups again but make sure to have a full backup of your site and database that you can revert to and do not enable the delete data option in Groups.

**Comment by PieterCooreman** [comment]
That fixed the problem. Thank you for your support. No idea how that file got corrupted.

**Comment by itthinx** [comment]
Perfect, really great to hear that it's ok now :)

Thanks for using Groups!
