### ISSUE TITLE
2.20 - Adds Widget Category Label (hierarchy?) when unwanted

### ISSUE THREAD

**Issue by nrooke** [itthinx/groups#148]
With no other edits/updates/content changes happening to the site in question, other than updating this plugin we are seeing some issues with the default Category Widget. Running 2.18 and even updating to 2.19 we see the following:
<img width="300" alt="pre-2 20" src="https://github.com/itthinx/groups/assets/682766/2a19b929-aad5-4780-9781-77378bc9d666">

After 2.20+:
<img width="291" alt="post-2 20" src="https://github.com/itthinx/groups/assets/682766/1c054e5c-f1fe-4a59-a564-2933e2f4914c">

**Comment by itthinx** [comment]
Hi, it seems that this was an issue with the title of your widget, but this is not related to Groups. If you still see this related, please let us know.
