### ISSUE TITLE
Automatically assign a role to a a group in woocommerce

### ISSUE THREAD

**Issue by MikaBean** [itthinx/groups#150]
Hello, 
I've seen that this question has been asked already, but I need more information.
I would like to automatically a specific role to a specific group.
Can you help me ? I've tried different shortcodes like
[groups_join role="GSS"]
but none of them worked.

Thank you for advance

**Comment by MikaBean** [comment]
Hello Itthinx,
can you provide me an answer please ? 
Have a nice day

**Comment by itthinx** [comment]
(resolved as above)
