### ISSUE TITLE
Groups > Options randomly resets?

### ISSUE THREAD

**Issue by charlesmulder** [itthinx/groups#154]
Good afternoon.

I have been using the plugin for about a year now and have noticed that the  `Groups > Options` settings randomly reverts to the default values. As far as I understand, those settings are using WordPress options, which means the values are persisted in the db. I'm stumped. Anyone else experience this issue? Any ideas?

PS
I'm using version `2.20.1` of the plugin and also [HyperDB](https://github.com/Automattic/HyperDB)

**Comment by proaktion** [comment]
Hi Charles,

To me this sounds very much like an issue with how your site retrieves data from its database, I would have thought it could be a database cache but as you mention HyperDB, maybe it's related to that. I would suggest to reach out to the support team for HyperDB to see if they know of similar cases and what steps you would need to apply to make sure that the options are not interfered with.

I'm closing this issue as this seems to be particular to your setup and not an issue with Groups. Feel free to follow up here if needed.
