### ISSUE TITLE
Groups 3.2.0 blocks break on WP 6.6 core update

### ISSUE THREAD

**Issue by ct-zen** [itthinx/groups#156]
After updating to WP core 6.6 and Groups 3.2.0, my existing groups blocks show up with:

"Your site doesn't include support for the Member block. You can try installing the block, convert it to a Custom HTML block, or remove it entirely."

I also lose the menu option to add Groups Member and Groups Non-member blocks.

I tried updating Groups to 3.2.0 before core update as well as after core update.  Regardless, the plugin features disappear once I'm running core 6.6.  Groups 3.2.0 on WP 6.5.5 works fine.

**Comment by proaktion** [comment]
Many thanks for reporting the issue, this has been fixed in version 3.2.1 which has just been released. Please give it a try and feel free to follow up if needed.

**Comment by proaktion** [comment]
...

**Comment by ct-zen** [comment]
> Many thanks for reporting the issue, this has been fixed in version 3.2.1 which has just been released. Please give it a try and feel free to follow up if needed.

Thanks for the update!  I'll give it a try next week.  Cheers!
