### ISSUE TITLE
spoted this todo and the Trac ticket is now marked as fixed

### ISSUE THREAD

**Issue by pbearne** [itthinx/groups#18]
in  class-groups-post-access.php

* @todo when wp_count_posts() provides reasonable filters, use them so that
 * the post counts displayed on top are in line with the actual posts that
 * are displayed in the table; same for wp_count_attachments()
 * @see http://core.trac.wordpress.org/ticket/16603
 *

**Comment by proaktion** [comment]
Thanks for pointing this out @pbearne , it's been a while but at last has been taken care of in the latest release.
