### ISSUE TITLE
Deprecated constructors

### ISSUE THREAD

**Issue by ekandreas** [itthinx/groups#37]
Getting this warning when using Groups in WP:

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Groups_Pagination has a deprecated constructor in .../plugins/groups/lib/core/class-groups-pagination.php on line 29

**Comment by ekandreas** [comment]
So it's fixed?

**Comment by proaktion** [comment]
Yes, thanks for reporting the issue. It was fixed in 1.10.0 - see also http://wordpress.org/support/topic/php-7-deprecated-constructor
