### ISSUE TITLE
Automatically remove a group upon user activation

### ISSUE THREAD

**Issue by middle8media** [itthinx/groups#52]
I have a Gravity membership registration form that assigns a "Pending" group upon submission.

As of now, the admin manually removes the "Pending" group once they activate the member, but I am wondering if it is possible to automatically remove that "Pending" group from the user once the admin activates their account?

**Comment by JoryHogeveen** [comment]
Hi @middle8media 

I don't think it's easy to build this logic automatically since this case could vary a lot for each implementation of Groups.

You could simple do this when a user is updated (or "activated").

```php

add_action( 'profile_update', 'my_theme_remove_pending_group' );
function my_theme_remove_pending_group() {
    $activated = false;
    // Check if your user is activated or not
    if ( true == $activated ) {
        $group_id = 1; // << change this to the ID of the "Pending" group
        // Here we delete this user from the "Pending" group
        Groups_User_Group::delete( $user_id, $group_id );
    }
}
```
