### ISSUE TITLE
groups_created_user_group Action not returning $group_id

### ISSUE THREAD

**Issue by Jursdotme** [itthinx/groups#55]
Im trying to send a mail when a user is added to a certain group, but the `groups_created_user_group` action isn't returning any group id ($group_id).

Im trying to use the action documented [here](http://docs.itthinx.com/document/groups/api/actions/).

**Comment by JoryHogeveen** [comment]
Did you set your action correctly to take two parameters?
By default WordPress only sends the first parameter unless you ask for more.

```php
// Default: this will only send one parameter
add_action( 'groups_created_user_group', 'my_callback' );

// This will send two parameters >> 10 is priority, 2 is number of parameters
add_action( 'groups_created_user_group', 'my_callback', 10, 2 );
```
