### ISSUE TITLE
Bypass group control by server access

### ISSUE THREAD

**Issue by Colir** [itthinx/groups#56]
Hi.
First at all thanks for this pugin, so useful!

On my WP, user can download the page in pdf format using the WKHTMLTOPDF lib.
The site is only accessible for registered user and some page need specific right managed with groups.

This work well.
However i have trouble when i generateing a pdf from a page protect by the groups plugin (and this is normal)

Here is my code

```
function template_redirect() {
    global $post;

    if( ( $_SERVER['REMOTE_ADDR'] == $_SERVER['SERVER_ADDR'] ) && isset($_GET['wkhtmltopdf']) ) return;

}
add_action( 'template_redirect',  'template_redirect'  );

```

How i can  tell to group that if the page is asked by the server itself, it can remove his control ?

thanks

**Comment by Colir** [comment]
please...

**Comment by itthinx** [comment]
The `groups_post_access_user_can_read_post` filter can be used to override the protection for that particular request. See https://docs.itthinx.com/document/groups/api/filters/ for details of that filter.
