### ISSUE TITLE
wp_cache_reset issue

### ISSUE THREAD

**Issue by ghost** [itthinx/groups#57]
Whenever I am trying to delete/switch a blog, I am getting this error in my apache log:

PHP Fatal error:  Uncaught Error: Call to undefined function wp_cache_reset() in <project-folder>/wp-content/plugins/groups/lib/core/class-groups-controller.php:46\nStack trace:\n#0 <project-folder>/wp-content/plugins/groups/lib/core/class-groups-controller.php(98): Groups_Controller::switch_to_blog(12)\n#1 <project-folder>/wp/wp-includes/plugin.php(524): Groups_Controller::delete_blog(12, true)\n#2 <project-folder>/wp/wp-admin/includes/ms.php(78): do_action('delete_blog', 12, true)\n#3 <project-folder>/wp/wp-admin/network/sites.php(133): wpmu_delete_blog(12, true)\n#4 {main}\n  thrown in <project-folder>/wp-content/plugins/groups/lib/core/class-groups-controller.php on line 46

My wordpress version is 4.6 .

Thanks.

**Comment by itthinx** [comment]
For the record, issues related to the use of the deprecated function wp_cache_reset() were addressed in versions 2.3.0 and 2.10.0.
