### ISSUE TITLE
Groups allows bypass of DISALLOW_FILE_EDIT & DISALLOW_FILE_MODS constants

### ISSUE THREAD

**Issue by majemedia** [itthinx/groups#58]
Hello,

I've set the following in my wp-config.php:

define( 'DISALLOW_FILE_EDIT', TRUE );
define( 'DISALLOW_FILE_MODS', TRUE );

These are being overridden by the Groups plugin. It's in place for security reasons.

When groups plugin is activated: Plugin/Theme Editing, Plugin installation/deletion/update display are allowed
When groups plugin is deactivated: The above is unavailable.

**Comment by proaktion** [comment]
Hi,

Please make sure that you don't have the administrator override in place - under Groups > Options - see also http://www.itthinx.com/plugins/groups/comment-page-9/#comment-526027

**Comment by majemedia** [comment]
@proaktion thanks for the tip. I guess I always I assumed (I know, right?) that unchecking that option would disable administrator permissions in the dashboard.

Unchecked.

**Comment by proaktion** [comment]
:) Ah no, it's useful for testing some stuff but not really needed normally.
