### ISSUE TITLE
Create SVG/Icon for the Groups icon + use dashicons in admin pages

### ISSUE THREAD

**Issue by JoryHogeveen** [itthinx/groups#60]
Currently the Groups icon is a PNG. Why not create a svg for this so all hovers etc in WP look nice :).

**Comment by JoryHogeveen** [comment]
Oh, and all the other icons can easily be replaced with dashicons aswell. Less assets!

**Comment by JoryHogeveen** [comment]
![image](https://cloud.githubusercontent.com/assets/826148/20020914/ef06c63a-a2d3-11e6-989e-7d8027021231.png)

**Comment by itthinx** [comment]
For the record, this was a good suggestion and svg icons were introduced in Groups 2.16.0 https://github.com/itthinx/groups/commit/3e592c7fd2b75b716aa50fc5f506b839198c9914
