### ISSUE TITLE
groups_created_group action conflicts with a BuddyPress Groups action of the same name

### ISSUE THREAD

**Issue by jeiseman** [itthinx/groups#70]
The "groups_created_group" action conflicts with a BuddyPress Groups action of the same name. Please consider renaming this action.

**Comment by proaktion** [comment]
Replied here https://wordpress.org/support/topic/groups_created_group-conflicts-with-buddypress/#post-9149965 and here https://buddypress.trac.wordpress.org/ticket/7504#comment:4
