### ISSUE TITLE
Warning: Illegal offset type

### ISSUE THREAD

**Issue by WarrenMoore** [itthinx/groups#73]
See https://wordpress.org/support/topic/warning-illegal-offset-type-7/ for example.

The issue is that `extend_for_orderby_groups_read` and `extend_for_filter_groups_read` both run on front-end AJAX calls to admin-ajax.php, where `post_type` can be an array.

It's an easy fix as I can't see a need for this to run on AJAX calls at all, and I'll add a pull request for this.

**Comment by proaktion** [comment]
Resolved in 2.2.0

See also https://github.com/itthinx/groups/pull/74
