### ISSUE TITLE
Important change in 2.2.0

### ISSUE THREAD

**Issue by ericelliott** [itthinx/groups#79]
In the 2.2.0 change log:

> Important change in this version: If access restrictions for post type are disabled, related entries will not be protected anymore.

What does this mean? This sounds like  a breaking change that could have a negative impact on my site. Is there detailed documentation of the impact of this change somewhere?

A similar change came along a while back that opened up access to all of my protected content to the whole world, which caused confusion with my users and exposed my protected content to the world. For somebody making a living from their site, that's a disaster.

Changes like that should be communicated in the strongest possible terms, with advance notice, and detailed instructions for changes to make in order to make a smooth transition possible.

Also, please look at [semver and breaking changes](https://medium.com/javascript-scene/software-versions-are-broken-3d2dc0da0783).

I suspect that most people using this plugin rely on it for income. Breaking changes are a big deal and need to be treated as such.

**Comment by proaktion** [comment]
> What does this mean?

Exactly what it says :) If you disable it for a specific post type, then any entry for that particular type of post will be unprotected. This shouldn't be a surprise, in fact it's much more consistent than the previous behavior, where even though you'd disable a specific post type, any access restrictions would still have been protected posts unless those were removed. The correction in this version means that if you disable a post type, it won't be checked for access restrictions which is quite logical. Technically, the query didn't take the post type into account when checking for access restrictions, now it does.

I hope that helps you understand what this change means. It's certainly not a breaking change BTW.
