### ISSUE TITLE
Post count in category widget showing all posts regardless of access

### ISSUE THREAD

**Issue by defunctl** [itthinx/groups#87]
How to reproduce:

1. Create numerous posts and restrict them to a group.
2. Assign a user to a group that has access to say just 1 post (or none) from the few you created.
3. Add the core Categories widget to the sidebar (check: show post counts)
4. Widget will show empty categories (hide_empty is on by default), and clicking on them shows a 404 not found (because the user doesn't have access to any posts in that category, but WordPress still considers it not empty and keeps showing it in the list).

Expected Result

A category should be considered empty if a user has access to 0 posts in that category and WordPress would no longer display it in the widget.

**Comment by itthinx** [comment]
Added support for updating the counts on Categories widgets (list or dropdown) to the https://github.com/itthinx/groups/tree/tested-2.20.0-6.4 branch for inclusion in the upcoming 2.20.0 release.

Also added support for this with the Categories block.
